//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 11:20:59 AM CST 
//


package org.hibernate.boot.jaxb.hbm.spi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.hibernate.engine.OptimisticLockStyle;


/**
 * 
 *                 Root entity mapping. Poorly named as entities do not have to be represented by
 *                 classes at all. Mapped entities may be represented via different methodologies
 *                 (POJO, Map, Dom4j).
 *             
 * 
 * <p>Java class for RootEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RootEntityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.hibernate.org/xsd/orm/hbm}EntityBaseDefinition"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tuplizer" type="{http://www.hibernate.org/xsd/orm/hbm}tuplizer-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="subselect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cache" type="{http://www.hibernate.org/xsd/orm/hbm}CacheType" minOccurs="0"/&gt;
 *         &lt;element name="natural-id-cache" type="{http://www.hibernate.org/xsd/orm/hbm}NaturalIdCacheType" minOccurs="0"/&gt;
 *         &lt;element name="synchronize" type="{http://www.hibernate.org/xsd/orm/hbm}synchronize-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="id" type="{http://www.hibernate.org/xsd/orm/hbm}SimpleIdType"/&gt;
 *           &lt;element name="composite-id" type="{http://www.hibernate.org/xsd/orm/hbm}CompositeIdType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="discriminator" type="{http://www.hibernate.org/xsd/orm/hbm}EntityDiscriminatorType" minOccurs="0"/&gt;
 *         &lt;element name="natural-id" type="{http://www.hibernate.org/xsd/orm/hbm}natural-id-type" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="version" type="{http://www.hibernate.org/xsd/orm/hbm}VersionAttributeType"/&gt;
 *           &lt;element name="timestamp" type="{http://www.hibernate.org/xsd/orm/hbm}TimestampAttributeType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="multi-tenancy" type="{http://www.hibernate.org/xsd/orm/hbm}multi-tenancy-type" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="idbag" type="{http://www.hibernate.org/xsd/orm/hbm}IdBagCollectionType"/&gt;
 *           &lt;group ref="{http://www.hibernate.org/xsd/orm/hbm}SingularAttributeGroup"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="join" type="{http://www.hibernate.org/xsd/orm/hbm}SecondaryTableType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *             &lt;element name="subclass" type="{http://www.hibernate.org/xsd/orm/hbm}DiscriminatorSubclassEntityType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="joined-subclass" type="{http://www.hibernate.org/xsd/orm/hbm}JoinedSubclassEntityType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element name="union-subclass" type="{http://www.hibernate.org/xsd/orm/hbm}UnionSubclassEntityType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="loader" type="{http://www.hibernate.org/xsd/orm/hbm}loader-type" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.hibernate.org/xsd/orm/hbm}CustomSqlDmlGroup"/&gt;
 *         &lt;element name="filter" type="{http://www.hibernate.org/xsd/orm/hbm}filter-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fetch-profile" type="{http://www.hibernate.org/xsd/orm/hbm}FetchProfileType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="resultset" type="{http://www.hibernate.org/xsd/orm/hbm}ResultSetMappingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;group ref="{http://www.hibernate.org/xsd/orm/hbm}NamedQueryGroup"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="catalog" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="check" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="discriminator-value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mutable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="optimistic-lock" type="{http://www.hibernate.org/xsd/orm/hbm}OptimisticLockStyleEnum" default="version" /&gt;
 *       &lt;attribute name="polymorphism" type="{http://www.hibernate.org/xsd/orm/hbm}PolymorphismEnum" default="implicit" /&gt;
 *       &lt;attribute name="rowid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="subselect" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="where" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootEntityType", propOrder = {
    "tuplizer",
    "subselect",
    "cache",
    "naturalIdCache",
    "synchronize",
    "comment",
    "id",
    "compositeId",
    "discriminator",
    "naturalId",
    "version",
    "timestamp",
    "multiTenancy",
    "attributes",
    "join",
    "subclass",
    "joinedSubclass",
    "unionSubclass",
    "loader",
    "sqlInsert",
    "sqlUpdate",
    "sqlDelete",
    "filter",
    "fetchProfile",
    "resultset",
    "query",
    "sqlQuery"
})
public class JaxbHbmRootEntityType
    extends JaxbHbmEntityBaseDefinition
    implements Serializable, EntityInfo, SecondaryTableContainer, TableInformationContainer, ToolingHintContainer
{

    protected List<JaxbHbmTuplizerType> tuplizer;
    protected String subselect;
    protected JaxbHbmCacheType cache;
    @XmlElement(name = "natural-id-cache")
    protected JaxbHbmNaturalIdCacheType naturalIdCache;
    protected List<JaxbHbmSynchronizeType> synchronize;
    protected String comment;
    protected JaxbHbmSimpleIdType id;
    @XmlElement(name = "composite-id")
    protected JaxbHbmCompositeIdType compositeId;
    protected JaxbHbmEntityDiscriminatorType discriminator;
    @XmlElement(name = "natural-id")
    protected JaxbHbmNaturalIdType naturalId;
    protected JaxbHbmVersionAttributeType version;
    protected JaxbHbmTimestampAttributeType timestamp;
    @XmlElement(name = "multi-tenancy")
    protected JaxbHbmMultiTenancyType multiTenancy;
    @XmlElements({
        @XmlElement(name = "idbag", type = JaxbHbmIdBagCollectionType.class),
        @XmlElement(name = "property", type = JaxbHbmBasicAttributeType.class),
        @XmlElement(name = "many-to-one", type = JaxbHbmManyToOneType.class),
        @XmlElement(name = "one-to-one", type = JaxbHbmOneToOneType.class),
        @XmlElement(name = "component", type = JaxbHbmCompositeAttributeType.class),
        @XmlElement(name = "dynamic-component", type = JaxbHbmDynamicComponentType.class),
        @XmlElement(name = "properties", type = JaxbHbmPropertiesType.class),
        @XmlElement(name = "any", type = JaxbHbmAnyAssociationType.class),
        @XmlElement(name = "map", type = JaxbHbmMapType.class),
        @XmlElement(name = "set", type = JaxbHbmSetType.class),
        @XmlElement(name = "list", type = JaxbHbmListType.class),
        @XmlElement(name = "bag", type = JaxbHbmBagCollectionType.class),
        @XmlElement(name = "array", type = JaxbHbmArrayType.class),
        @XmlElement(name = "primitive-array", type = JaxbHbmPrimitiveArrayType.class)
    })
    protected List<Serializable> attributes;
    protected List<JaxbHbmSecondaryTableType> join;
    protected List<JaxbHbmDiscriminatorSubclassEntityType> subclass;
    @XmlElement(name = "joined-subclass")
    protected List<JaxbHbmJoinedSubclassEntityType> joinedSubclass;
    @XmlElement(name = "union-subclass")
    protected List<JaxbHbmUnionSubclassEntityType> unionSubclass;
    protected JaxbHbmLoaderType loader;
    @XmlElement(name = "sql-insert")
    protected JaxbHbmCustomSqlDmlType sqlInsert;
    @XmlElement(name = "sql-update")
    protected JaxbHbmCustomSqlDmlType sqlUpdate;
    @XmlElement(name = "sql-delete")
    protected JaxbHbmCustomSqlDmlType sqlDelete;
    protected List<JaxbHbmFilterType> filter;
    @XmlElement(name = "fetch-profile")
    protected List<JaxbHbmFetchProfileType> fetchProfile;
    protected List<JaxbHbmResultSetMappingType> resultset;
    protected List<JaxbHbmNamedQueryType> query;
    @XmlElement(name = "sql-query")
    protected List<JaxbHbmNamedNativeQueryType> sqlQuery;
    @XmlAttribute(name = "catalog")
    protected String catalog;
    @XmlAttribute(name = "check")
    protected String check;
    @XmlAttribute(name = "discriminator-value")
    protected String discriminatorValue;
    @XmlAttribute(name = "mutable")
    protected Boolean mutable;
    @XmlAttribute(name = "optimistic-lock")
    @XmlJavaTypeAdapter(Adapter9 .class)
    protected OptimisticLockStyle optimisticLock;
    @XmlAttribute(name = "polymorphism")
    protected JaxbHbmPolymorphismEnum polymorphism;
    @XmlAttribute(name = "rowid")
    protected String rowid;
    @XmlAttribute(name = "schema")
    protected String schema;
    @XmlAttribute(name = "subselect")
    protected String subselectAttribute;
    @XmlAttribute(name = "table")
    protected String table;
    @XmlAttribute(name = "where")
    protected String where;

    /**
     * Gets the value of the tuplizer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tuplizer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTuplizer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmTuplizerType }
     * 
     * 
     */
    public List<JaxbHbmTuplizerType> getTuplizer() {
        if (tuplizer == null) {
            tuplizer = new ArrayList<JaxbHbmTuplizerType>();
        }
        return this.tuplizer;
    }

    /**
     * Gets the value of the subselect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubselect() {
        return subselect;
    }

    /**
     * Sets the value of the subselect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubselect(String value) {
        this.subselect = value;
    }

    /**
     * Gets the value of the cache property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmCacheType }
     *     
     */
    public JaxbHbmCacheType getCache() {
        return cache;
    }

    /**
     * Sets the value of the cache property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmCacheType }
     *     
     */
    public void setCache(JaxbHbmCacheType value) {
        this.cache = value;
    }

    /**
     * Gets the value of the naturalIdCache property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmNaturalIdCacheType }
     *     
     */
    public JaxbHbmNaturalIdCacheType getNaturalIdCache() {
        return naturalIdCache;
    }

    /**
     * Sets the value of the naturalIdCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmNaturalIdCacheType }
     *     
     */
    public void setNaturalIdCache(JaxbHbmNaturalIdCacheType value) {
        this.naturalIdCache = value;
    }

    /**
     * Gets the value of the synchronize property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synchronize property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynchronize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmSynchronizeType }
     * 
     * 
     */
    public List<JaxbHbmSynchronizeType> getSynchronize() {
        if (synchronize == null) {
            synchronize = new ArrayList<JaxbHbmSynchronizeType>();
        }
        return this.synchronize;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmSimpleIdType }
     *     
     */
    public JaxbHbmSimpleIdType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmSimpleIdType }
     *     
     */
    public void setId(JaxbHbmSimpleIdType value) {
        this.id = value;
    }

    /**
     * Gets the value of the compositeId property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmCompositeIdType }
     *     
     */
    public JaxbHbmCompositeIdType getCompositeId() {
        return compositeId;
    }

    /**
     * Sets the value of the compositeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmCompositeIdType }
     *     
     */
    public void setCompositeId(JaxbHbmCompositeIdType value) {
        this.compositeId = value;
    }

    /**
     * Gets the value of the discriminator property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmEntityDiscriminatorType }
     *     
     */
    public JaxbHbmEntityDiscriminatorType getDiscriminator() {
        return discriminator;
    }

    /**
     * Sets the value of the discriminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmEntityDiscriminatorType }
     *     
     */
    public void setDiscriminator(JaxbHbmEntityDiscriminatorType value) {
        this.discriminator = value;
    }

    /**
     * Gets the value of the naturalId property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmNaturalIdType }
     *     
     */
    public JaxbHbmNaturalIdType getNaturalId() {
        return naturalId;
    }

    /**
     * Sets the value of the naturalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmNaturalIdType }
     *     
     */
    public void setNaturalId(JaxbHbmNaturalIdType value) {
        this.naturalId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmVersionAttributeType }
     *     
     */
    public JaxbHbmVersionAttributeType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmVersionAttributeType }
     *     
     */
    public void setVersion(JaxbHbmVersionAttributeType value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmTimestampAttributeType }
     *     
     */
    public JaxbHbmTimestampAttributeType getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmTimestampAttributeType }
     *     
     */
    public void setTimestamp(JaxbHbmTimestampAttributeType value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the multiTenancy property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmMultiTenancyType }
     *     
     */
    public JaxbHbmMultiTenancyType getMultiTenancy() {
        return multiTenancy;
    }

    /**
     * Sets the value of the multiTenancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmMultiTenancyType }
     *     
     */
    public void setMultiTenancy(JaxbHbmMultiTenancyType value) {
        this.multiTenancy = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmIdBagCollectionType }
     * {@link JaxbHbmBasicAttributeType }
     * {@link JaxbHbmManyToOneType }
     * {@link JaxbHbmOneToOneType }
     * {@link JaxbHbmCompositeAttributeType }
     * {@link JaxbHbmDynamicComponentType }
     * {@link JaxbHbmPropertiesType }
     * {@link JaxbHbmAnyAssociationType }
     * {@link JaxbHbmMapType }
     * {@link JaxbHbmSetType }
     * {@link JaxbHbmListType }
     * {@link JaxbHbmBagCollectionType }
     * {@link JaxbHbmArrayType }
     * {@link JaxbHbmPrimitiveArrayType }
     * 
     * 
     */
    public List<Serializable> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<Serializable>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the join property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the join property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJoin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmSecondaryTableType }
     * 
     * 
     */
    public List<JaxbHbmSecondaryTableType> getJoin() {
        if (join == null) {
            join = new ArrayList<JaxbHbmSecondaryTableType>();
        }
        return this.join;
    }

    /**
     * Gets the value of the subclass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subclass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubclass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmDiscriminatorSubclassEntityType }
     * 
     * 
     */
    public List<JaxbHbmDiscriminatorSubclassEntityType> getSubclass() {
        if (subclass == null) {
            subclass = new ArrayList<JaxbHbmDiscriminatorSubclassEntityType>();
        }
        return this.subclass;
    }

    /**
     * Gets the value of the joinedSubclass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the joinedSubclass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJoinedSubclass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmJoinedSubclassEntityType }
     * 
     * 
     */
    public List<JaxbHbmJoinedSubclassEntityType> getJoinedSubclass() {
        if (joinedSubclass == null) {
            joinedSubclass = new ArrayList<JaxbHbmJoinedSubclassEntityType>();
        }
        return this.joinedSubclass;
    }

    /**
     * Gets the value of the unionSubclass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unionSubclass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnionSubclass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmUnionSubclassEntityType }
     * 
     * 
     */
    public List<JaxbHbmUnionSubclassEntityType> getUnionSubclass() {
        if (unionSubclass == null) {
            unionSubclass = new ArrayList<JaxbHbmUnionSubclassEntityType>();
        }
        return this.unionSubclass;
    }

    /**
     * Gets the value of the loader property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmLoaderType }
     *     
     */
    public JaxbHbmLoaderType getLoader() {
        return loader;
    }

    /**
     * Sets the value of the loader property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmLoaderType }
     *     
     */
    public void setLoader(JaxbHbmLoaderType value) {
        this.loader = value;
    }

    /**
     * Gets the value of the sqlInsert property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public JaxbHbmCustomSqlDmlType getSqlInsert() {
        return sqlInsert;
    }

    /**
     * Sets the value of the sqlInsert property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public void setSqlInsert(JaxbHbmCustomSqlDmlType value) {
        this.sqlInsert = value;
    }

    /**
     * Gets the value of the sqlUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public JaxbHbmCustomSqlDmlType getSqlUpdate() {
        return sqlUpdate;
    }

    /**
     * Sets the value of the sqlUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public void setSqlUpdate(JaxbHbmCustomSqlDmlType value) {
        this.sqlUpdate = value;
    }

    /**
     * Gets the value of the sqlDelete property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public JaxbHbmCustomSqlDmlType getSqlDelete() {
        return sqlDelete;
    }

    /**
     * Sets the value of the sqlDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmCustomSqlDmlType }
     *     
     */
    public void setSqlDelete(JaxbHbmCustomSqlDmlType value) {
        this.sqlDelete = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmFilterType }
     * 
     * 
     */
    public List<JaxbHbmFilterType> getFilter() {
        if (filter == null) {
            filter = new ArrayList<JaxbHbmFilterType>();
        }
        return this.filter;
    }

    /**
     * Gets the value of the fetchProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fetchProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFetchProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmFetchProfileType }
     * 
     * 
     */
    public List<JaxbHbmFetchProfileType> getFetchProfile() {
        if (fetchProfile == null) {
            fetchProfile = new ArrayList<JaxbHbmFetchProfileType>();
        }
        return this.fetchProfile;
    }

    /**
     * Gets the value of the resultset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmResultSetMappingType }
     * 
     * 
     */
    public List<JaxbHbmResultSetMappingType> getResultset() {
        if (resultset == null) {
            resultset = new ArrayList<JaxbHbmResultSetMappingType>();
        }
        return this.resultset;
    }

    /**
     * Gets the value of the query property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the query property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmNamedQueryType }
     * 
     * 
     */
    public List<JaxbHbmNamedQueryType> getQuery() {
        if (query == null) {
            query = new ArrayList<JaxbHbmNamedQueryType>();
        }
        return this.query;
    }

    /**
     * Gets the value of the sqlQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sqlQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSqlQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbHbmNamedNativeQueryType }
     * 
     * 
     */
    public List<JaxbHbmNamedNativeQueryType> getSqlQuery() {
        if (sqlQuery == null) {
            sqlQuery = new ArrayList<JaxbHbmNamedNativeQueryType>();
        }
        return this.sqlQuery;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalog(String value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the check property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheck() {
        return check;
    }

    /**
     * Sets the value of the check property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheck(String value) {
        this.check = value;
    }

    /**
     * Gets the value of the discriminatorValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminatorValue() {
        return discriminatorValue;
    }

    /**
     * Sets the value of the discriminatorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminatorValue(String value) {
        this.discriminatorValue = value;
    }

    /**
     * Gets the value of the mutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMutable() {
        if (mutable == null) {
            return true;
        } else {
            return mutable;
        }
    }

    /**
     * Sets the value of the mutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMutable(Boolean value) {
        this.mutable = value;
    }

    /**
     * Gets the value of the optimisticLock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public OptimisticLockStyle getOptimisticLock() {
        if (optimisticLock == null) {
            return new Adapter9().unmarshal("version");
        } else {
            return optimisticLock;
        }
    }

    /**
     * Sets the value of the optimisticLock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptimisticLock(OptimisticLockStyle value) {
        this.optimisticLock = value;
    }

    /**
     * Gets the value of the polymorphism property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHbmPolymorphismEnum }
     *     
     */
    public JaxbHbmPolymorphismEnum getPolymorphism() {
        if (polymorphism == null) {
            return JaxbHbmPolymorphismEnum.IMPLICIT;
        } else {
            return polymorphism;
        }
    }

    /**
     * Sets the value of the polymorphism property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHbmPolymorphismEnum }
     *     
     */
    public void setPolymorphism(JaxbHbmPolymorphismEnum value) {
        this.polymorphism = value;
    }

    /**
     * Gets the value of the rowid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowid() {
        return rowid;
    }

    /**
     * Sets the value of the rowid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowid(String value) {
        this.rowid = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the subselectAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubselectAttribute() {
        return subselectAttribute;
    }

    /**
     * Sets the value of the subselectAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubselectAttribute(String value) {
        this.subselectAttribute = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTable(String value) {
        this.table = value;
    }

    /**
     * Gets the value of the where property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhere() {
        return where;
    }

    /**
     * Sets the value of the where property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhere(String value) {
        this.where = value;
    }

}
