name: Reproducible build

on:
  push:
    branches:
    - main
    - 'releases/*'
  pull_request:
    branches:
    - '*'

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Gradle wrapper and dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/dists
        key: assemble-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
        restore-keys: |
          assemble-${{ runner.os }}-gradle-
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Prepare Gradle Enterprise credentials
      shell: bash
      run: |
        mkdir -p $HOME/.gradle/enterprise/
        echo "${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}" > $HOME/.gradle/enterprise/keys.properties
    - name: Build and compare checksums
      shell: bash
      run: |
        ./src/checkBuildReproducibility.sh
