executor: go-machine
parallelism: 2
steps:
  - checkout
  - run:
      name: Allow circleci user to restore Go modules cache
      command: |
        sudo mkdir /go
        sudo chown -R circleci:circleci /go
  - restore_go_cache
  - go_test
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
